// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbopswqhpogodcmcxacr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdib3Bzd3FocG9nb2RjbWN4YWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MDI0NjAsImV4cCI6MjA3Njk3ODQ2MH0.pqM0ULCX8DbKf8Ny9gev1cC1bh_2uSjZz8W1X93_3JU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});